import os
import re
import tempfile
from datetime import datetime
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT


def create_doc_from_text(text: str, title: str = "AI_Generated_Notes") -> str:
    """
    Premium note formatting for EasyNote AI.
    Designed for perfect readability in both Microsoft Word and Google Docs.
    """

    doc = Document()

    # -------------------------------
    # PAGE SETUP
    # -------------------------------
    section = doc.sections[0]
    section.top_margin = Inches(1)
    section.bottom_margin = Inches(1)
    section.left_margin = Inches(1)
    section.right_margin = Inches(1)

    base_font = "Arial"
    heading_color = RGBColor(30, 30, 30)
    body_color = RGBColor(25, 25, 25)
    gray = RGBColor(120, 120, 120)
    divider_gray = RGBColor(180, 180, 180)

    # -------------------------------
    # HEADER
    # -------------------------------
    title_para = doc.add_paragraph()
    title_para.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
    r = title_para.add_run(title)
    r.font.name = base_font
    r.font.size = Pt(18)
    r.font.bold = True
    r.font.color.rgb = heading_color
    title_para.paragraph_format.space_after = Pt(6)
    title_para.paragraph_format.space_before = Pt(12)

    subtitle = doc.add_paragraph(
        f"Generated by EasyNote AI • {datetime.now().strftime('%B %d, %Y')}"
    )
    subtitle.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
    for run in subtitle.runs:
        run.font.name = base_font
        run.font.size = Pt(10)
        run.font.color.rgb = gray
    subtitle.paragraph_format.space_after = Pt(10)

    divider = doc.add_paragraph("────────────────────────────────────────────")
    divider.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
    for r in divider.runs:
        r.font.name = base_font
        r.font.size = Pt(9)
        r.font.color.rgb = divider_gray
    divider.paragraph_format.space_after = Pt(16)

    # -------------------------------
    # FORMATTING HELPERS
    # -------------------------------
    def heading(txt):
        p = doc.add_paragraph(txt.strip())
        for r in p.runs:
            r.font.name = base_font
            r.font.size = Pt(14)
            r.font.bold = True
            r.font.color.rgb = heading_color
        p.paragraph_format.space_before = Pt(18)
        p.paragraph_format.space_after = Pt(10)
        return p

    def bullet(txt):
        p = doc.add_paragraph(txt.strip(), style="List Bullet")
        p.paragraph_format.left_indent = Inches(0.3)
        p.paragraph_format.space_after = Pt(5)
        for r in p.runs:
            r.font.name = base_font
            r.font.size = Pt(11)
            r.font.color.rgb = body_color
        return p

    def key_value(txt):
        if ":" not in txt:
            return bullet(txt)
        key, value = [x.strip() for x in txt.split(":", 1)]
        p = doc.add_paragraph()
        r1 = p.add_run(f"{key}: ")
        r1.font.bold = True
        r1.font.name = base_font
        r1.font.size = Pt(11)
        r1.font.color.rgb = body_color
        r2 = p.add_run(value)
        r2.font.name = base_font
        r2.font.size = Pt(11)
        r2.font.color.rgb = body_color
        p.paragraph_format.space_after = Pt(5)
        return p

    def textblock(txt):
        p = doc.add_paragraph(txt.strip())
        for r in p.runs:
            r.font.name = base_font
            r.font.size = Pt(11)
            r.font.color.rgb = body_color
        p.paragraph_format.line_spacing = 1.5
        p.paragraph_format.space_after = Pt(10)
        return p

    # -------------------------------
    # PARSING LOOP (based on #SECTION schema)
    # -------------------------------
    current_section = None
    for raw in text.splitlines():
        if not raw.strip():
            continue
        line = raw.strip()

        # Section headers
        if line.startswith("#SECTION "):
            heading(line.replace("#SECTION ", "").strip())
            current_section = line
            continue

        # Bullets
        if line.startswith("- "):
            key_value(line[2:].strip())
            continue

        # Fallback paragraph
        textblock(line)

    # -------------------------------
    # FOOTER
    # -------------------------------
    footer = section.footer.paragraphs[0]
    footer.text = "EasyNote AI • Everyday Intelligence"
    footer.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
    for r in footer.runs:
        r.font.size = Pt(9)
        r.font.name = base_font
        r.italic = True
        r.font.color.rgb = gray

    # -------------------------------
    # SAVE FILE
    # -------------------------------
    temp_dir = tempfile.gettempdir()
    safe_title = re.sub(r"[^\w\-]+", "_", title).strip("_")
    file_path = os.path.join(temp_dir, f"{safe_title}.docx")
    doc.save(file_path)
    return file_path
